# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: dbeaver
      POSTGRES_PASSWORD: weather
      POSTGRES_DB: weather_histrory

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080